export const FETCH_ALL_SCHOOLS_BEGIN="FETCH_ALL_SCHOOLS_BEGIN"
export const FETCH_ALL_SCHOOLS_ERROR="FETCH_ALL_SCHOOLS_ERROR"
export const FETCH_ALL_SCHOOLS_SUCCESS="FETCH_ALL_SCHOOLS_SUCCESS"
export const FETCH_SCHOOL_SETTING_BEGIN="FETCH_SCHOOL_SETTING_BEGIN"
export const FETCH_SCHOOL_SETTING_ERROR="FETCH_SCHOOL_SETTING_ERROR"
export const FETCH_SCHOOL_SETTING_SUCCESS="FETCH_SCHOOL_SETTING_SUCCESS"

//section
export const CREATE_SECTION_BEGIN="CREATE_SECTION_BEGIN"
export const CREATE_SECTION_SUCCESS="CREATE_SECTION_SUCCESS"
export const CREATE_SECTION_ERROR="CREATE_SECTION_ERROR"
export const FETCH_ALL_SECTION_BEGIN="FETCH_ALL_SECTION_BEGIN"
export const FETCH_ALL_SECTION_ERROR="FETCH_ALL_SECTION_ERROR"
export const FETCH_ALL_SECTION_SUCCESS="FETCH_ALL_SECTION_SUCCESS"

//class
export const CREATE_CLASSES_BEGIN="CREATE_CLASSES_BEGIN"
export const CREATE_CLASSES_SUCCESS="CREATE_CLASSES_SUCCESS"
export const CREATE_CLASSES_ERROR="CREATE_CLASSES_ERROR"
export const FETCH_ALL_CLASSES_BEGIN="FETCH_ALL_CLASSES_BEGIN"
export const FETCH_ALL_CLASSES_ERROR="FETCH_ALL_CLASSES_ERROR"
export const FETCH_ALL_CLASSES_SUCCESS="FETCH_ALL_CLASSES_SUCCESS"

//arm
export const CREATE_ARM_BEGIN="CREATE_ARM_BEGIN"
export const CREATE_ARM_SUCCESS="CREATE_ARM_SUCCESS"
export const CREATE_ARM_ERROR="CREATE_ARM_ERROR"
export const FETCH_ALL_ARM_BEGIN="FETCH_ALL_ARM_BEGIN"
export const FETCH_ALL_ARM_ERROR="FETCH_ALL_ARM_ERROR"
export const FETCH_ALL_ARM_SUCCESS="FETCH_ALL_ARM_SUCCESS"

//student
export const CREATE_STUDENT_BEGIN="CREATE_STUDENT_BEGIN"
export const CREATE_STUDENT_SUCCESS="CREATE_STUDENT_SUCCESS"
export const CREATE_STUDENT_ERROR="CREATE_STUDENT_ERROR"
export const EDIT_STUDENT_BEGIN="EDIT_STUDENT_BEGIN"
export const EDIT_STUDENT_SUCCESS="EDIT_STUDENT_SUCCESS"
export const EDIT_STUDENT_ERROR="EDIT_STUDENT_ERROR"
export const FETCH_ALL_STUDENT_BEGIN="FETCH_ALL_STUDENT_BEGIN"
export const FETCH_ALL_STUDENT_ERROR="FETCH_ALL_STUDENT_ERROR"
export const FETCH_ALL_STUDENT_SUCCESS="FETCH_ALL_STUDENT_SUCCESS"
export const FETCH_GRAPH_STUDENT_TOTAL_BY_CLASS_BEGIN="FETCH_GRAPH_STUDENT_TOTAL_BY_CLASS_ERROR_BEGIN"
export const FETCH_GRAPH_STUDENT_TOTAL_BY_CLASS_ERROR="FETCH_GRAPH_STUDENT_TOTAL_BY_CLASS_ERROR"
export const FETCH_GRAPH_STUDENT_TOTAL_BY_CLASS_SUCCESS="FETCH_GRAPH_STUDENT_TOTAL_BY_CLASS_SUCCESS"
export const FETCH_STUDENT_CURRENT_CLASS_AND_ARM="FETCH_STUDENT_CURRENT_CLASS_AND_ARM"


//staff 
export const CREATE_STAFF_BEGIN="CREATE_STAFF_BEGIN"
export const CREATE_STAFF_SUCCESS="CREATE_STAFF_SUCCESS"
export const CREATE_STAFF_ERROR="CREATE_STAFF_ERROR"
export const FETCH_ALL_STAFF_BEGIN="FETCH_ALL_STAFF_BEGIN"
export const FETCH_ALL_STAFF_ERROR="FETCH_ALL_STAFF_ERROR"
export const FETCH_ALL_STAFF_SUCCESS="FETCH_ALL_STAFF_SUCCESS"
export const FETCH_CURRENT_STAFF_BEGIN="FETCH_CURRENT_STAFF_BEGIN"
export const FETCH_CURRENT_STAFF_ERROR="FETCH_CURRENT_STAFF_ERROR"
export const FETCH_CURRENT_STAFF_SUCCESS="FETCH_CURRENT_STAFF_SUCCESS"

//subject and class
export const CREATE_SUBJECT_BEGIN="CREATE_SUBJECT_BEGIN"
export const CREATE_SUBJECT_SUCCESS="CREATE_SUBJECT_SUCCESS"
export const CREATE_SUBJECT_ERROR="CREATE_SUBJECT_ERROR"
export const FETCH_ALL_SUBJECTS_BEGIN="FETCH_ALL_SUBJECTS_BEGIN"
export const FETCH_ALL_SUBJECTS_ERROR="FETCH_ALL_SUBJECTS_ERROR"
export const FETCH_ALL_SUBJECTS_SUCCESS="FETCH_ALL_SUBJECTS_SUCCESS"
export const FETCH_ALL_SUBJECTS_IN_CURRENT_CLASS_BEGIN="FETCH_ALL_SUBJECTS_IN_CURRENT_CLASS_BEGIN"
export const FETCH_ALL_SUBJECTS_IN_CURRENT_CLASS_ERROR="FETCH_ALL_SUBJECTS_IN_CURRENT_CLASS_ERROR"
export const FETCH_ALL_SUBJECTS_IN_CURRENT_CLASS_SUCCESS="FETCH_ALL_SUBJECTS_IN_CURRENT_CLASS_SUCCESS"
export const FETCH_ALL_TESTS_IN_CURRENT_CLASS_BEGIN="FETCH_ALL_TESTS_IN_CURRENT_CLASS_BEGIN"
export const FETCH_ALL_TESTS_IN_CURRENT_CLASS_ERROR="FETCH_ALL_TESTS_IN_CURRENT_CLASS_ERROR"
export const FETCH_ALL_TESTS_IN_CURRENT_CLASS_SUCCESS="FETCH_ALL_TESTS_IN_CURRENT_CLASS_SUCCESS"
export const ADD_ClASS_TESTS_BEGIN="ADD_CLASS_TESTS_BEGIN"
export const ADD_CLASS_TESTS_SUCCESS="ADD_CLASS_TESTS_SUCCESS"
export const ADD_CLASS_TESTS_ERROR="ADD_CLASS_TESTS_ERROR"
export const REMOVE_CLASS_TESTS_BEGIN="REMOVE_CLASS_TESTS_BEGIN"
export const REMOVE_CLASS_TESTS_SUCCESS="REMOVE_CLASS_TESTS_SUCCESS"
export const REMOVE_CLASS_TESTS_ERROR="REMOVE_CLASS_TESTS_ERROR"
export const ADD_CLASS_SUBJECT_BEGIN="ADD_CLASS_SUBJECT_BEGIN"
export const ADD_CLASS_SUBJECT_SUCCESS="ADD_CLASS_SUBJECT_SUCCESS"
export const ADD_CLASS_SUBJECT_ERROR="ADD_CLASS_SUBJECT_ERROR"
export const REMOVE_CLASS_SUBJECT_BEGIN="REMOVE_CLASS_SUBJECT_BEGIN"
export const REMOVE_CLASS_SUBJECT_SUCCESS="REMOVE_CLASS_SUBJECT_SUCCESS"
export const REMOVE_CLASS_SUBJECT_ERROR="REMOVE_CLASS_SUBJECT_ERROR"

//auth 
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_USER_SETTING= "GET_USER_SETTING";
export const TOKEN_LOCATION="gsgsgs"
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

///department 
export const CREATE_DEPARTMENT_BEGIN="CREATE_DEPARTMENT_BEGIN"
export const CREATE_DEPARTMENT_SUCCESS="CREATE_DEPARTMENT_SUCCESS"
export const CREATE_DEPARTMENT_ERROR="CREATE_DEPARTMENT_ERROR"
export const EDIT_DEPARTMENT_BEGIN="EDIT_DEPARTMENT_BEGIN"
export const EDIT_DEPARTMENT_SUCCESS="EDIT_DEPARTMENT_SUCCESS"
export const EDIT_DEPARTMENT_ERROR="EDIT_DEPARTMENT_ERROR"
export const FETCH_ALL_DEPARTMENT_BEGIN="FETCH_ALL_DEPARTMENT_BEGIN"
export const FETCH_ALL_DEPARTMENT_ERROR="FETCH_ALL_DEPARTMENT_ERROR"
export const FETCH_ALL_DEPARTMENT_SUCCESS="FETCH_ALL_DEPARTMENT_SUCCESS"

//desgination
export const CREATE_DESIGNATION_BEGIN="CREATE_DESIGNATION_BEGIN"
export const CREATE_DESIGNATION_SUCCESS="CREATE_DESIGNATION_SUCCESS"
export const CREATE_DESIGNATION_ERROR="CREATE_DESIGNATION_ERROR"
export const EDIT_DESIGNATION_BEGIN="EDIT_DESIGNATION_BEGIN"
export const EDIT_DESIGNATION_SUCCESS="EDIT_DESIGNATION_SUCCESS"
export const EDIT_DESIGNATION_ERROR="EDIT_DESIGNATION_ERROR"
export const FETCH_ALL_DESIGNATION_BEGIN="FETCH_ALL_DESIGNATION_BEGIN"
export const FETCH_ALL_DESIGNATION_ERROR="FETCH_ALL_DESIGNATION_ERROR"
export const FETCH_ALL_DESIGNATION_SUCCESS="FETCH_ALL_DESIGNATION_SUCCESS"

//skill
export const CREATE_SKILL_BEGIN="CREATE_SKILL_BEGIN"
export const CREATE_SKILL_SUCCESS="CREATE_SKILL_SUCCESS"
export const CREATE_SKILL_ERROR="CREATE_SKILL_ERROR"
export const FETCH_ALL_SKILL_BEGIN="FETCH_ALL_SKILL_BEGIN"
export const FETCH_ALL_SKILL_ERROR="FETCH_ALL_SKILL_ERROR"
export const FETCH_ALL_SKILL_SUCCESS="FETCH_ALL_SKILL_SUCCESS"
export const FETCH_ALL_SKILL_IN_CURRENT_SECTION_BEGIN="FETCH_ALL_SKILL_IN_CURRENT_SECTION_BEGIN"
export const FETCH_ALL_SKILL_IN_CURRENT_SECTION_ERROR="FETCH_ALL_SKILL_IN_CURRENT_SECTION_ERROR"
export const FETCH_ALL_SKILL_IN_CURRENT_SECTION_SUCCESS="FETCH_ALL_SKILL_IN_CURRENT_SECTION_SUCCESS"
export const ADD_SECTION_SKILL_BEGIN="ADD_SECTION_SKILL_BEGIN"
export const ADD_SECTION_SKILL_SUCCESS="ADD_SECTION_SKILL_SUCCESS"
export const ADD_SECTION_SKILL_ERROR="ADD_SECTION_SKILL_ERROR"
export const REMOVE_SECTION_SKILL_BEGIN="REMOVE_SECTION_SKILL_BEGIN"
export const REMOVE_SECTION_SKILL_SUCCESS="REMOVE_SECTION_SKILL_SUCCESS"
export const REMOVE_SECTION_SKILL_ERROR="REMOVE_SECTION_SKILL_ERROR"
export const FETCH_All_SKILL_SCORE_BEGIN="FETCH_All_SKILL_SCORE_BEGIN"
export const FETCH_All_SKILL_SCORE_SUCCESS="FETCH_All_SKILL_SCORE_SUCCESS"
export const FETCH_All_SKILL_SCORE_ERROR="FETCH_All_SKILL_SCORE_ERROR"

//Test
export const CREATE_TEST_BEGIN="CREATE_TEST_BEGIN"
export const CREATE_TEST_SUCCESS="CREATE_TEST_SUCCESS"
export const CREATE_TEST_ERROR="CREATE_TEST_ERROR"
export const FETCH_ALL_TEST_BEGIN="FETCH_ALL_TEST_BEGIN"
export const FETCH_ALL_TEST_ERROR="FETCH_ALL_TEST_ERROR"
export const FETCH_ALL_TEST_SUCCESS="FETCH_ALL_TEST_SUCCESS"
export const FETCH_STUDENT_TEST_SCORE_BY_SUBJECT_BEGIN="FETCH_STUDENT_TEST_SCORE_BY_SUBJECT_BEGIN"
export const FETCH_STUDENT_TEST_SCORE_BY_SUBJECT_SUCCESS="FETCH_STUDENT_TEST_SCORE_BY_SUBJECT_SUCCESS"
export const FETCH_STUDENT_TEST_SCORE_BY_SUBJECT_ERROR="FETCH_STUDENT_TEST_SCORE_BY_SUBJECT_ERROR"
export const FETCH_All_STUDENT_TEST_BEGIN="FETCH_All_STUDENT_TEST_BEGIN"
export const FETCH_All_STUDENT_TEST_SUCCESS="FETCH_All_STUDENT_TEST_SUCCESS"
export const FETCH_All_STUDENT_TEST_ERROR="FETCH_All_STUDENT_TEST_ERROR"
export const FETCH_CURRENT_STUDENT_BEGIN="FETCH_CURRENT_STUDENT_BEGIN"
export const FETCH_CURRENT_STUDENT_SUCCESS="FETCH_CURRENT_STUDENT_SUCCESS"
export const FETCH_CURRENT_STUDENT_ERROR="FETCH_CURRENT_STUDENT_ERROR"
export const VALIDATE_STUDENTS_SCORE_BY_SUBJECTS="VALIDATE_STUDENTS_SCORE_BY_SUBJECTS"

//Behaviour
export const CREATE_BEHAVIOUR_BEGIN="CREATE_BEHAVIOUR_BEGIN"
export const CREATE_BEHAVIOUR_SUCCESS="CREATE_BEHAVIOUR_SUCCESS"
export const CREATE_BEHAVIOUR_ERROR="CREATE_BEHAVIOUR_ERROR"
export const FETCH_ALL_BEHAVIOUR_BEGIN="FETCH_ALL_BEHAVIOUR_BEGIN"
export const FETCH_ALL_BEHAVIOUR_ERROR="FETCH_ALL_BEHAVIOUR_ERROR"
export const FETCH_ALL_BEHAVIOUR_SUCCESS="FETCH_ALL_BEHAVIOUR_SUCCESS"
export const FETCH_ALL_BEHAVIOUR_IN_CURRENT_SECTION_BEGIN="FETCH_ALL_BEHAVIOUR_IN_CURRENT_SECTION_BEGIN"
export const FETCH_ALL_BEHAVIOUR_IN_CURRENT_SECTION_ERROR="FETCH_ALL_BEHAVIOUR_IN_CURRENT_SECTION_ERROR"
export const FETCH_ALL_BEHAVIOUR_IN_CURRENT_SECTION_SUCCESS="FETCH_ALL_BEHAVIOUR_IN_CURRENT_SECTION_SUCCESS"
export const ADD_SECTION_BEHAVIOUR_BEGIN="ADD_SECTION_BEHAVIOUR_BEGIN"
export const ADD_SECTION_BEHAVIOUR_SUCCESS="ADD_SECTION_BEHAVIOUR_SUCCESS"
export const ADD_SECTION_BEHAVIOUR_ERROR="ADD_SECTION_BEHAVIOUR_ERROR"
export const REMOVE_SECTION_BEHAVIOUR_BEGIN="REMOVE_SECTION_BEHAVIOUR_BEGIN"
export const REMOVE_SECTION_BEHAVIOUR_SUCCESS="REMOVE_SECTION_BEHAVIOUR_SUCCESS"
export const REMOVE_SECTION_BEHAVIOUR_ERROR="REMOVE_SECTION_BEHAVIOUR_ERROR"
export const FETCH_All_BEHAVIOUR_SCORE_BEGIN="FETCH_All_BEHAVIOUR_SCORE_BEGIN"
export const FETCH_All_BEHAVIOUR_SCORE_SUCCESS="FETCH_All_BEHAVIOUR_SCORE_SUCCESS"
export const FETCH_All_BEHAVIOUR_SCORE_ERROR="FETCH_All_BEHAVIOUR_SCORE_ERROR"


//SMS
export const FETCH_SCHOOL_BALANCE="FETCH_SCHOOL_BALANCE"
export const FETCH_SCHOOL_MESSAGES="FETCH_SCHOOL_MESSAGES"



///parts
// export const url ="http://localhost:4000"
// export const school= `5f8c7ee1b9776e05f105a6db`

// export const url ="http://localhost:4000"
// export const school= `606dd5e4ad1a8604c70e1151`



 export const url ="https://plotapi-tets.herokuapp.com"	
 export const school= `5f9183cad035174e94992476`


//  export const url ="https://demoplot.herokuapp.com"	
// //  export const school= `606f1167be0e6c00153f0460`

export const student= 'student'
export const staff= 'staff'


//scratchCard

export const FETCH_SCRATCH_CARD_STATS="FETCH_SCRATCH_CARD_STATS"
export const FETCH_SCRATCH_CARDS_BEGIN="FETCH_SCRATCH_CARD_BEGIN"
export const FETCH_SCRATCH_CARDS_SUCCESS="FETCH_SCRATCH_CARD_SUCCESS"
export const FETCH_SCRATCH_CARDS_ERROR="FETCH_SCRATCH_CARD_ERROR"
export const DELETE_SCRATCH_CARD="DELETE_SCRATCH_CARD"
export const GENERATE_SCRATCH_CARD="GENERATE_SCRATCH_CARD"
